### ISSUE TITLE
Difference between this and Traefik 2 Helm Chart?

### ISSUE THREAD

**Issue by doug62** [sleighzy/k3s-traefik-v2-kubernetes-crd#15]
Thanks for this excellent repo, I am new to K3s and I'm wondering what is the difference between https://github.com/traefik/traefik-helm-chart/tree/master/traefik and this (aside from you examples and explainations).

Thanks

**Comment by sleighzy** [comment]
Hi @doug62 , thanks for that. Probably not much for the core pieces, although I haven't used that helm chart so couldn't honestly say. My original content began life as a local migration of a Docker Compose deployment to K3s. Thanks for highlighting the helm chart, I'll dig through it in greater depth to determine what would be needed to create an updated `values.yaml` file to generate the same configuration I have now. If successful I'll document and provide as an option here.

The examples and explanations are a great help to me (bad memory) and others so has been an evolution as I've learned more over time.
